name: Merge 2 m3u Files

on:
  push:
    branches: [main]
  repository_dispatch:
    types: [merge-files]

jobs:

  merge-files:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Merge files
      run: |
        # 克隆其他仓库
        git clone https://github.com/YueChan/IPTV.git IPTV        
        # 合并文件
        cat IPTV/IPTV.m3u IPTV/Global.m3u > IPTV.m3u
        
        # 将合并后的文件添加到您的仓库
        git config --global user.email "yupeng007@gmail.com"
        git config --global user.name "yupeng007@gmail.com"
        git add merged IPTV.m3u
        git commit -m "Merge IPTV.m3u from other repository"
        git push
        
    - name: Trigger workflow on other repo push
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: Merge Files
        token: ${{ secrets.PERSONAL_TOKEN }}
        repo: yupengoo7/IPTV
        ref: "refs/heads/main"
        inputs: '{}'