name: Merge M3U Files

on:
  push:
    branches:
      - main

jobs:
  merge-m3u:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch other repository
        uses: actions/fetch-repo@v3
        with:
          repo: YueChan/IPTV
          ref: main
          path: IPTV
      - name: Merge M3U files
        run: |
          cat YueChan/IPTV.m3u YueChan/Global.m3u > IPTV.m3u
      - name: Commit merged M3U file
        run: |
          git config user.name "yupengoo7"
          git config user.email "yupeng007@gmail.com"
          git add IPTV.m3u
          git commit -m "Merge M3U files"
          git push
