name: Concat M3U Files

on:
  push:
    branches:

      • main

jobs:
  concat:
    runs-on: ubuntu-latest
    steps:

      • uses: actions/checkout@v3

      • name: Get m3u file 1 from other repo
        uses: Lucas-C/http-request-action@v1
        with:
          url: https://raw.githubusercontent.com/YueChan/Live/main/IPTV.m3u
          method: GET
          save_as: IPTV.m3u

      • name: Get m3u file 2 from other repo
        uses: Lucas-C/http-request-action@v1
        with:
          url: https://raw.githubusercontent.com/YueChan/Live/main/Global.m3u
          method: GET
          save_as: Global.m3u

      • uses: appleboy/github-actions/blob/master/actions/concat@v1
        with:
          args: IPTV.m3u,Global.m3u > IPTV.m3u
